- name: Install Apache and start the service
  hosts: all
  vars:
    web_pkg: httpd
    web_service: httpd
    python_pkg: python-httplib2
    rule: http

  tasks:
    - name: Install the required packages
      yum:
        name:
          - "{{ web_pkg }}"
          - "{{ python_pkg }}"
        state: latest

    - name: Start and enable the {{ firewall_service }} service
      service:
        name: "{{ firewall_service }}"
        enabled: true
        state: started

    - name: Create web content to be served
      copy:
        content: "Example web content"
        dest: /var/www/html/index.html

    - name: Open the port for {{ rule }}
      firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled

